# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: macos-latest
    strategy:
        matrix: 
          destination: ['platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Build
        run: |
          cd Example
          pod install
          xcodebuild clean build -workspace AllowX.xcworkspace -scheme AllowX-Example -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
       
      - name: Lint
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings  
